# Use Node.js as the base image
FROM node:latest

# Set the working dir in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working dir
COPY  package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the current dir to the working dir
COPY  . .

#Build the Next.js application
RUN npm run build

#Expose the port that the Next.js app runs on
EXPOSE  3000

#Set environment variable for production
ENV NODE_ENV=production

# Start the Next.js app
CMD [ "npm" ,"start"]